CREATE TABLE IF NOT EXISTS customers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  contact VARCHAR(100) DEFAULT '',
  email VARCHAR(255) DEFAULT '',
  opening_date DATE DEFAULT CURRENT_DATE,
  amount_credited DECIMAL(12,2) DEFAULT 0,
  account_balance DECIMAL(12,2) DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS customer_transactions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  customer_id INT NOT NULL,
  date_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  products_bought TEXT,
  amount_paid DECIMAL(12,2) DEFAULT 0,
  amount_credited DECIMAL(12,2) DEFAULT 0,
  sold_by VARCHAR(255),
  FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE
);


ALTER TABLE customers ADD COLUMN opening_date DATE DEFAULT CURDATE();